name:                WeatherWander
version:             0.1.0.0
github:              "shashankyadav03/WeatherWander"
license:             MIT
author:              "Shashank Yadav"
maintainer:          "s.yadav@qmul.ac.uk"
copyright:           "Copyright (c) 2023 Shashank Yadav"

extra-source-files:
- README.md
- ChangeLog.md

# Dependencies of the library.
library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - aeson
    - http-client
    - http-conduit
    - text
    - persistent
    - persistent-sqlite

# Executables
executables:
  WeatherWander-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - WeatherWander

# Test suites
tests:
  WeatherWander-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:         -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - WeatherWander

# Benchmark configuration
# benchmarks:
#   WeatherWander-bench:
#     main:                Benchmarks.hs
#     source-dirs:         benchmark
#     ghc-options:         -threaded -rtsopts -with-rtsopts=-N
#     dependencies:
#       - WeatherWander
