# Specifies the Stackage snapshot to use:
resolver: lts-18.10

# Local packages, usually specified by relative directory name
packages:
- .

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.7.1"

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
extra-deps:
  - aeson-1.5.6.0
  - http-client-0.7.8
  - http-conduit-2.3.8
  - optparse-applicative-0.16.1.0
  - persistent-2.13.1.2
  - persistent-sqlite-2.13.0.3
  - text-1.2.4.1

# Override default flag values for local packages and extra-deps
# flags: {}

# GHC options
# ghc-options: {}

# Control whether a GHC install is allowed
# install-ghc: true

# Apply GHC options to everything (including dependencies)
# apply-ghc-options: everything

# The directory in which stack will store snapshots
# snapshot-location-base: ".stack-work/downloaded"

# Local binaries
# local-bin-path: "./.stack-work/bin"
